base:
  is_smote: True
  random_seed: 42
  test_size: 0.2

preprocess:
  categorical_columns: ['family_status', 'goods_category', 'position', 'employment_status', 'education']
  numeric_categorical_columns: ['snils', 'gender', 'merch_code', 'child_count', 'loan_term']
  money_columns: ['month_profit', 'month_expense', 'loan_amount']

train:
  random_forest:
    n_estimators: [50, 100, 150]
